version: '3.8'

services:
  unbound:
    runtime: runsc-overlay-host-network
    image: ghcr.io/glassrom/dns-docker:master
    read_only: true
    container_name: unbound
    user: "970:970"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_SYS_RESOURCE
      - CAP_NET_RAW
    tmpfs:
      - /tmp
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: always
    pull_policy: always
    networks:
      aakdns_net:
        ipv4_address: 172.18.0.2

networks:
  aakdns_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
